# Header | 主菜单
menu:
  - title: 首页
    url: /
    intro: "首页"
    icon: "fa fa-home"
  - title: 归档
    url: /archives
    intro: "所有文章"
    icon: "fa fa-archive"
  - title: 分类
    url: /categories
    intro: "全部分类"
    icon: "fa fa-folder"
  - title: 标签
    url: tags
    intro: "全部标签"
    icon: "fa fa-tags"
  - title: 关于
    url: /about
    intro: "关于本站"
    icon: "fa fa-user"

# set header height | 设置导航栏高度 px
header_height: 60

# Small icon of Your site | 站点小图标地址
favicon: img/favicon.png

# Link to your avatar | 填写头像地址
avatar: img/avatar.jpg

# set cursor | 设置鼠标指针图标
cursor:
  on: true
  normal: img/cursor/normal.cur # 默认指针
  link: img/cursor/link.cur # 链接指针