# Header | 主菜单
menu:
  - title: 首页
    url: /
    intro: "首页"
    icon: "fa fa-home"
  - title: 归档
    url: /archives
    intro: "所有文章"
    icon: "fa fa-archive"
  - title: 关于
    url: /about
    intro: "关于本站"
    icon: "fa fa-user"

# Small icon of Your site | 站点小图标地址
favicon: img/favicon.png

# Link to your avatar | 填写头像地址
avatar: img/head.jpg

# set cursor | 设置鼠标指针图标
cursor:
  normal: img/cursor/normal.cur # 初始指针
  link: img/cursor/link.cur # 链接指针